swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints of functionality for transactions
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Transactions Module
      summary: User Transactions
      description: API to display the transactions list of the current month, display one of them, and add, modify or delete information about a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: query
          name: month
          description: Month to retrieve transactions for (in YYYY-MM format)
          type: string
          required: false
          default: current month
        - in: query
          name: sort
          description: The sort order for the transactions. Possible values are 'asc' (ascending) and 'desc' (descending).
          required: false
          type: string
          default: desc
      produces:
        - application/json
      responses:
        "200":
          description: User transactions retrieved successfully
          schema:
            type: array
            items:
                      $ref: "#/definitions/Transaction" 
        "400":
            description: Bad Request ( the request parameters are invalid or missing.)
        "401":
            description: Unauthorized 
        "403":
            description: Forbidden
        "404":
            description: Not Found ( the requested transactions are not available.)
        "429":
            description: Too Many Requests ( the number of requests made by the user exceeds the allowed limit.)
        "500":
            description: Internal Server Error    
          
  /user/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - Module Single transaction
      summary: User Single Transaction
      description: API to display one of transaction by Id in list of transactions
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: User transaction retrieved successfully
          schema:
            type: array
            items:
                      $ref: "#/definitions/Transaction" 
        "400":
          description: Bad Request (the request parameters are invalid or missing)
        "401":
          description: Unauthorized (authentication failed)
        "403":
          description: Forbidden (insufficient permission)
        '404':
          description: Not Found (the requested transaction was not found)
        '429':
          description: Too Many Requests (the number of requests made by the user exceeds the allowed limit)
        '500':
          description: Internal Server Error
          
    patch:
      security:
        - Bearer: []
      tags:
        - Module Single transaction
      summary: User Single Transaction API
      description: API for creating, updating or deleting an information of a transaction by Id in the list of transactions of current month
      operationId: PatchTransactionInfos
      parameters:
        - in: path
          name: transactionId
          description: ID of transaction to fetch
          required: true
          type: string
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: body
          name: body
          description: Action and new information to modify of this transaction Payload
          required: true
          schema:
            type: object
            properties:
              category:
                type: string
              notes:
                type: string
      responses:
        "200":
          description: User information's transaction is modified successfully
          schema:
            type: array
            items:
              $ref: "#/definitions/Transaction" 
        "400":
          description: Bad Request (the request parameters are invalid or missing)
        "401":
          description: Unauthorized 
        "403":
          description: Forbidden
        "404":
          description: Not Found (the requested transactions are not available)
        "429":
          description: Too Many Requests (the number of requests made by the user exceeds the allowed limit)
        "500":
          description: Internal Server Error    
  
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
    
definitions:
  Transaction:
      type: object
      properties:
        id:
          type: string
          description: transaction's ID
        date:
          type: string
          description: transaction's date
          format: date-time
        description:
          type: string
          description: transaction's description
        amount:
          type: integer
          description: transaction's amount
        balance:
          type: integer
          description: account balance after transaction
        transactionType:
          type: object
          description: Type of transaction 
          example: Electronic' or 'mandat' or 'check
        category:
          type: string
          description: transaction's category
          example: 'Restaurant'
        notes:
          type: string
          description: transaction's notes
          example: 'It was very expensive and the portions were so small'
              